on:
  workflow_call:
    inputs:
      checkout_keystore:
        description: 'Whether to checkout keystore repository'
        required: false
        type: boolean
        default: false
      version_name:
        description: 'Version name for the APK'
        required: false
        type: string
        default: ''
      version_code:
        description: 'Version code for the APK'
        required: false
        type: string
        default: ''

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  VERSION_NAME: ${{ inputs.version_name }}
  VERSION_CODE: ${{ inputs.version_code }}

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          cache: 'gradle'
          
      - name: Decode Keystore
        if: inputs.checkout_keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$KEYSTORE_BASE64" ]; then
            mkdir -p app/keystore
            echo "$KEYSTORE_BASE64" | base64 --decode > app/keystore/main.jks
          fi

      - name: Build APK
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: bash ./gradlew :app:assembleRelease --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: logfox-release
          compression-level: 0
          path: app/build/outputs/apk/release/LogFox-*.apk
