on:
  workflow_call:
    inputs:
      version_name:
        description: 'Version name for the APK'
        required: false
        type: string
        default: ''
      version_code:
        description: 'Version code for the APK'
        required: false
        type: string
        default: ''

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  VERSION_NAME: ${{ inputs.version_name }}
  VERSION_CODE: ${{ inputs.version_code }}

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          cache: 'gradle'

      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: logfox-debug
          compression-level: 0
          path: app/build/outputs/apk/debug/LogFox-*.apk
